-- Seed REFERENTIEL + CATEGORIES for Finance SaaS
-- Run this once in Supabase SQL Editor

INSERT INTO referentiel ("Categorie", "Sous_Categorie", "Sens", "Frequence", "Statut", "Compteur_N", "Montant_Cumule") VALUES
('Revenu','Salaire','IN','Mensuel','ACTIF',0,0.0),
('Revenu','Vente','IN','Ponctuel','ACTIF',0,0.0),
('Revenu','Remboursement','IN','Ponctuel','ACTIF',0,0.0),
('Revenu','Allocation Familiale','IN','Mensuel','ACTIF',0,0.0),
('Revenu','Freelance','IN','Ponctuel','ACTIF',0,0.0),
('Revenu','Loyer','IN','Mensuel','ACTIF',0,0.0),
('Revenu','Dons','IN','Ponctuel','ACTIF',0,0.0),
('Revenu','Bricolage','IN','Ponctuel','ACTIF',0,0.0),
('Revenu','Prime','IN','Ponctuel','ACTIF',0,0.0),
('Revenu','Revenu_Autre','IN','Mensuel','ACTIF',0,0.0),
('Logement','Loyer','OUT','Mensuel','ACTIF',0,0.0),
('Logement','Logement_autre','OUT','Ponctuel','ACTIF',0,0.0),
('Logement','Impôts','OUT','Annuel','ACTIF',0,0.0),
('Logement','Electricité & Eau','OUT','Mensuel','ACTIF',0,0.0),
('Logement','Entretien & Maison','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Courses maison','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Protéine','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Alimentation','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Fruits & légumes','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Snacks & Boissons','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Restaurant rapide & fast food','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Vie Quotidienne_Autre','OUT','Ponctuel','ACTIF',0,0.0),
('Transport','Carburant','OUT','Ponctuel','ACTIF',0,0.0),
('Transport','Tramway & Bus','OUT','Ponctuel','ACTIF',0,0.0),
('Transport','Taxi & Uber','OUT','Ponctuel','ACTIF',0,0.0),
('Transport','Entretien & Lavage','OUT','Ponctuel','ACTIF',0,0.0),
('Transport','Assurance & Vignette','OUT','Annuel','ACTIF',0,0.0),
('Transport','Parking & Péage','OUT','Ponctuel','ACTIF',0,0.0),
('Transport','Transport_Autre','OUT','Ponctuel','ACTIF',0,0.0),
('Loisirs','Sorties & Shopping','OUT','Ponctuel','ACTIF',0,0.0),
('Loisirs','Ciné & Culture','OUT','Ponctuel','ACTIF',0,0.0),
('Loisirs','Voyages & Weekend','OUT','Ponctuel','ACTIF',0,0.0),
('Loisirs','Sport & Hobby','OUT','Ponctuel','ACTIF',0,0.0),
('Loisirs','Bien-être & Hygiène','OUT','Ponctuel','ACTIF',0,0.0),
('Loisirs','Cadeaux & Dons','OUT','Ponctuel','ACTIF',0,0.0),
('Loisirs','Loisirs_Autre','OUT','Ponctuel','ACTIF',0,0.0),
('Abonnements','Télécom & Internet','OUT','Mensuel','ACTIF',0,0.0),
('Abonnements','Streaming & TV','OUT','Mensuel','ACTIF',0,0.0),
('Abonnements','Club & Gym','OUT','Mensuel','ACTIF',0,0.0),
('Abonnements','Logiciels & Cloud','OUT','Mensuel','ACTIF',0,0.0),
('Abonnements','Banque & Assur','OUT','Mensuel','ACTIF',0,0.0),
('Abonnements','Abonnements_autre','OUT','Mensuel','ACTIF',0,0.0),
('Santé','Pharmacie','OUT','Ponctuel','ACTIF',0,0.0),
('Santé','Consultations','OUT','Ponctuel','ACTIF',0,0.0),
('Santé','Analyses & Radio','OUT','Ponctuel','ACTIF',0,0.0),
('Santé','Optique','OUT','Ponctuel','ACTIF',0,0.0),
('Santé','Santé_autre','OUT','Ponctuel','ACTIF',0,0.0),
('Finances & Crédits','Crédit Conso ou Auto','OUT','Mensuel','ACTIF',0,0.0),
('Finances & Crédits','Épargne','OUT','Mensuel','ACTIF',0,0.0),
('Finances & Crédits','Remboursement Dette','OUT','Ponctuel','ACTIF',0,0.0),
('Finances & Crédits','Frais Bancaires','OUT','Ponctuel','ACTIF',0,0.0),
('Finances & Crédits','EPARGNE INVESTISSEMENT','OUT','Variable','ACTIF',0,0.0),
('Divers','Generale','OUT','Ponctuel','ACTIF',0,0.0),
('Divers','Frais de dossier','OUT','Ponctuel','ACTIF',0,0.0),
('Divers','Amendes','OUT','Ponctuel','ACTIF',0,0.0),
('Divers','Administratif','OUT','Ponctuel','ACTIF',0,0.0),
('Divers','Objets du quotidien','OUT','Ponctuel','ACTIF',0,0.0),
('Divers','Divers_Autre','OUT','Ponctuel','ACTIF',0,0.0)
ON CONFLICT ("Categorie", "Sous_Categorie") DO NOTHING;

INSERT INTO categories ("Categorie", "Sous_Categorie", "Plafond") VALUES
('Revenu','Salaire',0.0),
('Revenu','Vente',0.0),
('Revenu','Remboursement',0.0),
('Revenu','Allocation Familiale',0.0),
('Revenu','Freelance',0.0),
('Revenu','Loyer',0.0),
('Revenu','Dons',0.0),
('Revenu','Bricolage',0.0),
('Revenu','Prime',0.0),
('Revenu','Revenu_Autre',0.0),
('Logement','Loyer',0.0),
('Logement','Logement_autre',0.0),
('Logement','Impôts',0.0),
('Logement','Electricité & Eau',0.0),
('Logement','Entretien & Maison',0.0),
('Vie Quotidienne','Courses maison',0.0),
('Vie Quotidienne','Protéine',0.0),
('Vie Quotidienne','Alimentation',0.0),
('Vie Quotidienne','Fruits & légumes',0.0),
('Vie Quotidienne','Snacks & Boissons',0.0),
('Vie Quotidienne','Restaurant rapide & fast food',0.0),
('Vie Quotidienne','Vie Quotidienne_Autre',0.0),
('Transport','Carburant',0.0),
('Transport','Tramway & Bus',0.0),
('Transport','Taxi & Uber',0.0),
('Transport','Entretien & Lavage',0.0),
('Transport','Assurance & Vignette',0.0),
('Transport','Parking & Péage',0.0),
('Transport','Transport_Autre',0.0),
('Loisirs','Sorties & Shopping',0.0),
('Loisirs','Ciné & Culture',0.0),
('Loisirs','Voyages & Weekend',0.0),
('Loisirs','Sport & Hobby',0.0),
('Loisirs','Bien-être & Hygiène',0.0),
('Loisirs','Cadeaux & Dons',0.0),
('Loisirs','Loisirs_Autre',0.0),
('Abonnements','Télécom & Internet',0.0),
('Abonnements','Streaming & TV',0.0),
('Abonnements','Club & Gym',0.0),
('Abonnements','Logiciels & Cloud',0.0),
('Abonnements','Banque & Assur',0.0),
('Abonnements','Abonnements_autre',0.0),
('Santé','Pharmacie',0.0),
('Santé','Consultations',0.0),
('Santé','Analyses & Radio',0.0),
('Santé','Optique',0.0),
('Santé','Santé_autre',0.0),
('Finances & Crédits','Crédit Conso ou Auto',0.0),
('Finances & Crédits','Épargne',0.0),
('Finances & Crédits','Remboursement Dette',0.0),
('Finances & Crédits','Frais Bancaires',0.0),
('Finances & Crédits','EPARGNE INVESTISSEMENT',0.0),
('Divers','Generale',0.0),
('Divers','Frais de dossier',0.0),
('Divers','Amendes',0.0),
('Divers','Administratif',0.0),
('Divers','Objets du quotidien',0.0),
('Divers','Divers_Autre',0.0)
ON CONFLICT ("Categorie", "Sous_Categorie") DO NOTHING;

-- ── DICO_MATCHING (dictionnaire de classification) ──────────────────────────
-- Mots-clés → Catégorie/Sous_Catégorie pour le Trieur fuzzy

INSERT INTO "DICO_MATCHING" ("Sens", "Mot_Cle", "Categorie_Cible", "Sous_Categorie_Cible") VALUES
-- Revenus (IN)
('IN','SALAIRE','Revenu','Salaire'),
('IN','VIREMENT SALAIRE','Revenu','Salaire'),
('IN','PAIE','Revenu','Salaire'),
('IN','VENTE','Revenu','Vente'),
('IN','REMBOURSEMENT','Revenu','Remboursement'),
('IN','CNSS','Revenu','Allocation Familiale'),
('IN','ALLOCATION','Revenu','Allocation Familiale'),
('IN','FREELANCE','Revenu','Freelance'),
('IN','MISSION','Revenu','Freelance'),
('IN','LOYER RECU','Revenu','Loyer'),
('IN','DON','Revenu','Dons'),
('IN','PRIME','Revenu','Prime'),
('IN','BONUS','Revenu','Prime'),
-- Logement (OUT)
('OUT','LOYER','Logement','Loyer'),
('OUT','SYNDIC','Logement','Logement_autre'),
('OUT','IMPOT','Logement','Impôts'),
('OUT','TAXE','Logement','Impôts'),
('OUT','LYDEC','Logement','Electricité & Eau'),
('OUT','REDAL','Logement','Electricité & Eau'),
('OUT','AMENDIS','Logement','Electricité & Eau'),
('OUT','ONEE','Logement','Electricité & Eau'),
('OUT','ELECTRICITE','Logement','Electricité & Eau'),
('OUT','EAU','Logement','Electricité & Eau'),
('OUT','BRICOLAGE','Logement','Entretien & Maison'),
('OUT','PLOMBIER','Logement','Entretien & Maison'),
('OUT','ELECTROMENAGER','Logement','Entretien & Maison'),
('OUT','IKEA','Logement','Entretien & Maison'),
('OUT','KITEA','Logement','Entretien & Maison'),
-- Vie Quotidienne (OUT)
('OUT','MARJANE','Vie Quotidienne','Courses maison'),
('OUT','CARREFOUR','Vie Quotidienne','Courses maison'),
('OUT','ACIMA','Vie Quotidienne','Courses maison'),
('OUT','ASWAK ASSALAM','Vie Quotidienne','Courses maison'),
('OUT','BIM','Vie Quotidienne','Courses maison'),
('OUT','LABEL VIE','Vie Quotidienne','Courses maison'),
('OUT','ATACADAO','Vie Quotidienne','Courses maison'),
('OUT','SUPERMARCHE','Vie Quotidienne','Courses maison'),
('OUT','COURSES','Vie Quotidienne','Courses maison'),
('OUT','EPICERIE','Vie Quotidienne','Courses maison'),
('OUT','HANOUT','Vie Quotidienne','Courses maison'),
('OUT','BOUCHERIE','Vie Quotidienne','Protéine'),
('OUT','POULET','Vie Quotidienne','Protéine'),
('OUT','VIANDE','Vie Quotidienne','Protéine'),
('OUT','POISSON','Vie Quotidienne','Protéine'),
('OUT','SOUK','Vie Quotidienne','Fruits & légumes'),
('OUT','LEGUMES','Vie Quotidienne','Fruits & légumes'),
('OUT','FRUITS','Vie Quotidienne','Fruits & légumes'),
('OUT','PRIMEUR','Vie Quotidienne','Fruits & légumes'),
('OUT','CAFE','Vie Quotidienne','Snacks & Boissons'),
('OUT','SNACK','Vie Quotidienne','Snacks & Boissons'),
('OUT','PATISSERIE','Vie Quotidienne','Snacks & Boissons'),
('OUT','BOULANGERIE','Vie Quotidienne','Snacks & Boissons'),
('OUT','PAUL','Vie Quotidienne','Snacks & Boissons'),
('OUT','STARBUCKS','Vie Quotidienne','Snacks & Boissons'),
('OUT','MCDONALD','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','MCDO','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','BURGER KING','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','KFC','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','PIZZA','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','TACOS','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','RESTAURANT','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','RESTO','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','LIVRAISON','Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','GLOVO','Vie Quotidienne','Restaurant rapide & fast food'),
-- Transport (OUT)
('OUT','ESSENCE','Transport','Carburant'),
('OUT','GASOIL','Transport','Carburant'),
('OUT','STATION','Transport','Carburant'),
('OUT','AFRIQUIA','Transport','Carburant'),
('OUT','SHELL','Transport','Carburant'),
('OUT','TOTAL','Transport','Carburant'),
('OUT','CARBURANT','Transport','Carburant'),
('OUT','TRAMWAY','Transport','Tramway & Bus'),
('OUT','TRAM','Transport','Tramway & Bus'),
('OUT','ALSA','Transport','Tramway & Bus'),
('OUT','TAXI','Transport','Taxi & Uber'),
('OUT','UBER','Transport','Taxi & Uber'),
('OUT','INDRIVER','Transport','Taxi & Uber'),
('OUT','CAREEM','Transport','Taxi & Uber'),
('OUT','LAVAGE','Transport','Entretien & Lavage'),
('OUT','VIDANGE','Transport','Entretien & Lavage'),
('OUT','MECANICIEN','Transport','Entretien & Lavage'),
('OUT','GARAGE','Transport','Entretien & Lavage'),
('OUT','PNEU','Transport','Entretien & Lavage'),
('OUT','ASSURANCE AUTO','Transport','Assurance & Vignette'),
('OUT','VIGNETTE','Transport','Assurance & Vignette'),
('OUT','VISITE TECHNIQUE','Transport','Assurance & Vignette'),
('OUT','PARKING','Transport','Parking & Péage'),
('OUT','PEAGE','Transport','Parking & Péage'),
('OUT','AUTOROUTE','Transport','Parking & Péage'),
-- Loisirs (OUT)
('OUT','ZARA','Loisirs','Sorties & Shopping'),
('OUT','H&M','Loisirs','Sorties & Shopping'),
('OUT','DECATHLON','Loisirs','Sorties & Shopping'),
('OUT','SHOPPING','Loisirs','Sorties & Shopping'),
('OUT','VETEMENT','Loisirs','Sorties & Shopping'),
('OUT','CHAUSSURE','Loisirs','Sorties & Shopping'),
('OUT','CINEMA','Loisirs','Ciné & Culture'),
('OUT','MEGARAMA','Loisirs','Ciné & Culture'),
('OUT','IMAX','Loisirs','Ciné & Culture'),
('OUT','LIVRE','Loisirs','Ciné & Culture'),
('OUT','VOYAGE','Loisirs','Voyages & Weekend'),
('OUT','HOTEL','Loisirs','Voyages & Weekend'),
('OUT','RIAD','Loisirs','Voyages & Weekend'),
('OUT','AIRBNB','Loisirs','Voyages & Weekend'),
('OUT','RYANAIR','Loisirs','Voyages & Weekend'),
('OUT','ROYAL AIR MAROC','Loisirs','Voyages & Weekend'),
('OUT','ONCF','Loisirs','Voyages & Weekend'),
('OUT','TRAIN','Loisirs','Voyages & Weekend'),
('OUT','SPORT','Loisirs','Sport & Hobby'),
('OUT','SALLE DE SPORT','Loisirs','Sport & Hobby'),
('OUT','PISCINE','Loisirs','Sport & Hobby'),
('OUT','FOOTBALL','Loisirs','Sport & Hobby'),
('OUT','COIFFEUR','Loisirs','Bien-être & Hygiène'),
('OUT','BARBIER','Loisirs','Bien-être & Hygiène'),
('OUT','HAMMAM','Loisirs','Bien-être & Hygiène'),
('OUT','PARFUM','Loisirs','Bien-être & Hygiène'),
('OUT','COSMETIQUE','Loisirs','Bien-être & Hygiène'),
('OUT','CADEAU','Loisirs','Cadeaux & Dons'),
('OUT','ANNIVERSAIRE','Loisirs','Cadeaux & Dons'),
('OUT','MARIAGE','Loisirs','Cadeaux & Dons'),
-- Abonnements (OUT)
('OUT','MAROC TELECOM','Abonnements','Télécom & Internet'),
('OUT','INWI','Abonnements','Télécom & Internet'),
('OUT','ORANGE','Abonnements','Télécom & Internet'),
('OUT','INTERNET','Abonnements','Télécom & Internet'),
('OUT','WIFI','Abonnements','Télécom & Internet'),
('OUT','FORFAIT','Abonnements','Télécom & Internet'),
('OUT','RECHARGE','Abonnements','Télécom & Internet'),
('OUT','NETFLIX','Abonnements','Streaming & TV'),
('OUT','SPOTIFY','Abonnements','Streaming & TV'),
('OUT','YOUTUBE','Abonnements','Streaming & TV'),
('OUT','DISNEY','Abonnements','Streaming & TV'),
('OUT','APPLE MUSIC','Abonnements','Streaming & TV'),
('OUT','GYM','Abonnements','Club & Gym'),
('OUT','FITNESS','Abonnements','Club & Gym'),
('OUT','CLUB','Abonnements','Club & Gym'),
('OUT','CHATGPT','Abonnements','Logiciels & Cloud'),
('OUT','CLAUDE','Abonnements','Logiciels & Cloud'),
('OUT','GITHUB','Abonnements','Logiciels & Cloud'),
('OUT','ADOBE','Abonnements','Logiciels & Cloud'),
('OUT','MICROSOFT','Abonnements','Logiciels & Cloud'),
('OUT','GOOGLE ONE','Abonnements','Logiciels & Cloud'),
('OUT','ICLOUD','Abonnements','Logiciels & Cloud'),
('OUT','BANQUE','Abonnements','Banque & Assur'),
('OUT','ASSURANCE','Abonnements','Banque & Assur'),
('OUT','CIH','Abonnements','Banque & Assur'),
('OUT','BMCE','Abonnements','Banque & Assur'),
('OUT','ATTIJARIWAFA','Abonnements','Banque & Assur'),
('OUT','BANQUE POPULAIRE','Abonnements','Banque & Assur'),
-- Santé (OUT)
('OUT','PHARMACIE','Santé','Pharmacie'),
('OUT','MEDICAMENT','Santé','Pharmacie'),
('OUT','PARAPHARMACIE','Santé','Pharmacie'),
('OUT','MEDECIN','Santé','Consultations'),
('OUT','DOCTEUR','Santé','Consultations'),
('OUT','DENTISTE','Santé','Consultations'),
('OUT','CLINIQUE','Santé','Consultations'),
('OUT','HOPITAL','Santé','Consultations'),
('OUT','ANALYSE','Santé','Analyses & Radio'),
('OUT','RADIO','Santé','Analyses & Radio'),
('OUT','SCANNER','Santé','Analyses & Radio'),
('OUT','LABO','Santé','Analyses & Radio'),
('OUT','LUNETTES','Santé','Optique'),
('OUT','OPTICIEN','Santé','Optique'),
('OUT','LENTILLES','Santé','Optique'),
-- Finances & Crédits (OUT)
('OUT','CREDIT','Finances & Crédits','Crédit Conso ou Auto'),
('OUT','ECHEANCE','Finances & Crédits','Crédit Conso ou Auto'),
('OUT','MENSUALITE','Finances & Crédits','Crédit Conso ou Auto'),
('OUT','EPARGNE','Finances & Crédits','Épargne'),
('OUT','INVESTISSEMENT','Finances & Crédits','Épargne'),
('OUT','DETTE','Finances & Crédits','Remboursement Dette'),
('OUT','FRAIS BANCAIRES','Finances & Crédits','Frais Bancaires'),
('OUT','COMMISSION','Finances & Crédits','Frais Bancaires'),
-- Divers (OUT)
('OUT','AMENDE','Divers','Amendes'),
('OUT','CONTRAVENTION','Divers','Amendes'),
('OUT','TIMBRE','Divers','Administratif'),
('OUT','NOTAIRE','Divers','Administratif'),
('OUT','DOSSIER','Divers','Frais de dossier'),
('OUT','TELEPHONE','Divers','Objets du quotidien'),
('OUT','SAMSUNG','Divers','Objets du quotidien'),
('OUT','APPLE','Divers','Objets du quotidien'),
('OUT','IPHONE','Divers','Objets du quotidien')
ON CONFLICT ("Sens", "Mot_Cle") DO NOTHING;
