-- seed_referentiel.sql — Structure simplifiée v2
-- 9 catégories · 40 sous-catégories
-- Run once in Supabase SQL Editor (PostgreSQL)

INSERT INTO referentiel ("Categorie","Sous_Categorie","Sens","Frequence","Statut","Compteur_N","Montant_Cumule") VALUES
-- Revenus (IN) — 5 sous-catégories
('Revenu','Salaire',                        'IN', 'Mensuel',  'ACTIF',0,0.0),
('Revenu','Freelance & Activités',          'IN', 'Ponctuel', 'ACTIF',0,0.0),
('Revenu','Aides & Allocations',            'IN', 'Ponctuel', 'ACTIF',0,0.0),
('Revenu','Prime & Bonus',                  'IN', 'Ponctuel', 'ACTIF',0,0.0),
('Revenu','Revenu_Autre',                   'IN', 'Ponctuel', 'ACTIF',0,0.0),
-- Logement (OUT) — 4 sous-catégories
('Logement','Loyer',                        'OUT','Mensuel',  'ACTIF',0,0.0),
('Logement','Electricité & Eau',            'OUT','Mensuel',  'ACTIF',0,0.0),
('Logement','Entretien & Maison',           'OUT','Ponctuel', 'ACTIF',0,0.0),
('Logement','Charges & Taxes',              'OUT','Annuel',   'ACTIF',0,0.0),
-- Vie Quotidienne (OUT) — 5 sous-catégories
('Vie Quotidienne','Courses maison',        'OUT','Ponctuel', 'ACTIF',0,0.0),
('Vie Quotidienne','Alimentation',          'OUT','Ponctuel', 'ACTIF',0,0.0),
('Vie Quotidienne','Snacks & Boissons',     'OUT','Ponctuel', 'ACTIF',0,0.0),
('Vie Quotidienne','Restaurant rapide & fast food','OUT','Ponctuel','ACTIF',0,0.0),
('Vie Quotidienne','Vie Quotidienne_Autre', 'OUT','Ponctuel', 'ACTIF',0,0.0),
-- Transport (OUT) — 6 sous-catégories
('Transport','Carburant',                   'OUT','Ponctuel', 'ACTIF',0,0.0),
('Transport','Taxi & Transports',           'OUT','Ponctuel', 'ACTIF',0,0.0),
('Transport','Entretien & Réparation',      'OUT','Ponctuel', 'ACTIF',0,0.0),
('Transport','Assurance & Vignette',        'OUT','Annuel',   'ACTIF',0,0.0),
('Transport','Parking & Péage',             'OUT','Ponctuel', 'ACTIF',0,0.0),
('Transport','Transport_Autre',             'OUT','Ponctuel', 'ACTIF',0,0.0),
-- Loisirs (OUT) — 5 sous-catégories
('Loisirs','Sorties & Culture',             'OUT','Ponctuel', 'ACTIF',0,0.0),
('Loisirs','Voyages & Weekend',             'OUT','Ponctuel', 'ACTIF',0,0.0),
('Loisirs','Sport & Bien-être',             'OUT','Ponctuel', 'ACTIF',0,0.0),
('Loisirs','Cadeaux & Dons',                'OUT','Ponctuel', 'ACTIF',0,0.0),
('Loisirs','Loisirs_Autre',                 'OUT','Ponctuel', 'ACTIF',0,0.0),
-- Abonnements (OUT) — 4 sous-catégories
('Abonnements','Télécom & Internet',        'OUT','Mensuel',  'ACTIF',0,0.0),
('Abonnements','Streaming & Apps',          'OUT','Mensuel',  'ACTIF',0,0.0),
('Abonnements','Club & Gym',                'OUT','Mensuel',  'ACTIF',0,0.0),
('Abonnements','Abonnements_autre',         'OUT','Mensuel',  'ACTIF',0,0.0),
-- Santé (OUT) — 4 sous-catégories
('Santé','Pharmacie',                       'OUT','Ponctuel', 'ACTIF',0,0.0),
('Santé','Médecin & Examens',               'OUT','Ponctuel', 'ACTIF',0,0.0),
('Santé','Optique',                         'OUT','Ponctuel', 'ACTIF',0,0.0),
('Santé','Santé_autre',                     'OUT','Ponctuel', 'ACTIF',0,0.0),
-- Finances & Crédits (OUT) — 3 sous-catégories
('Finances & Crédits','Crédit & Remboursement',  'OUT','Mensuel','ACTIF',0,0.0),
('Finances & Crédits','Épargne & Investissement','OUT','Mensuel','ACTIF',0,0.0),
('Finances & Crédits','Frais Bancaires',         'OUT','Ponctuel','ACTIF',0,0.0),
-- Divers (OUT) — 4 sous-catégories
('Divers','Administratif',                  'OUT','Ponctuel', 'ACTIF',0,0.0),
('Divers','Amendes',                        'OUT','Ponctuel', 'ACTIF',0,0.0),
('Divers','Objets du quotidien',            'OUT','Ponctuel', 'ACTIF',0,0.0),
('Divers','Divers_Autre',                   'OUT','Ponctuel', 'ACTIF',0,0.0)
ON CONFLICT ("Categorie","Sous_Categorie") DO NOTHING;

INSERT INTO categories ("Categorie","Sous_Categorie","Plafond") VALUES
('Revenu','Salaire',0.0),
('Revenu','Freelance & Activités',0.0),
('Revenu','Aides & Allocations',0.0),
('Revenu','Prime & Bonus',0.0),
('Revenu','Revenu_Autre',0.0),
('Logement','Loyer',0.0),
('Logement','Electricité & Eau',0.0),
('Logement','Entretien & Maison',0.0),
('Logement','Charges & Taxes',0.0),
('Vie Quotidienne','Courses maison',0.0),
('Vie Quotidienne','Alimentation',0.0),
('Vie Quotidienne','Snacks & Boissons',0.0),
('Vie Quotidienne','Restaurant rapide & fast food',0.0),
('Vie Quotidienne','Vie Quotidienne_Autre',0.0),
('Transport','Carburant',0.0),
('Transport','Taxi & Transports',0.0),
('Transport','Entretien & Réparation',0.0),
('Transport','Assurance & Vignette',0.0),
('Transport','Parking & Péage',0.0),
('Transport','Transport_Autre',0.0),
('Loisirs','Sorties & Culture',0.0),
('Loisirs','Voyages & Weekend',0.0),
('Loisirs','Sport & Bien-être',0.0),
('Loisirs','Cadeaux & Dons',0.0),
('Loisirs','Loisirs_Autre',0.0),
('Abonnements','Télécom & Internet',0.0),
('Abonnements','Streaming & Apps',0.0),
('Abonnements','Club & Gym',0.0),
('Abonnements','Abonnements_autre',0.0),
('Santé','Pharmacie',0.0),
('Santé','Médecin & Examens',0.0),
('Santé','Optique',0.0),
('Santé','Santé_autre',0.0),
('Finances & Crédits','Crédit & Remboursement',0.0),
('Finances & Crédits','Épargne & Investissement',0.0),
('Finances & Crédits','Frais Bancaires',0.0),
('Divers','Administratif',0.0),
('Divers','Amendes',0.0),
('Divers','Objets du quotidien',0.0),
('Divers','Divers_Autre',0.0)
ON CONFLICT ("Categorie","Sous_Categorie") DO NOTHING;

-- ── DICO_MATCHING ─────────────────────────────────────────────────────────────
INSERT INTO "DICO_MATCHING" ("Sens","Mot_Cle","Categorie_Cible","Sous_Categorie_Cible") VALUES
-- Revenus (IN)
('IN','SALAIRE',          'Revenu','Salaire'),
('IN','VIREMENT SALAIRE', 'Revenu','Salaire'),
('IN','PAIE',             'Revenu','Salaire'),
('IN','VENTE',            'Revenu','Freelance & Activités'),
('IN','FREELANCE',        'Revenu','Freelance & Activités'),
('IN','MISSION',          'Revenu','Freelance & Activités'),
('IN','BRICOLAGE',        'Revenu','Freelance & Activités'),
('IN','CNSS',             'Revenu','Aides & Allocations'),
('IN','ALLOCATION',       'Revenu','Aides & Allocations'),
('IN','REMBOURSEMENT',    'Revenu','Aides & Allocations'),
('IN','DON',              'Revenu','Aides & Allocations'),
('IN','PRIME',            'Revenu','Prime & Bonus'),
('IN','BONUS',            'Revenu','Prime & Bonus'),
('IN','LOYER RECU',       'Revenu','Revenu_Autre'),
-- Logement (OUT)
('OUT','LOYER',           'Logement','Loyer'),
('OUT','LYDEC',           'Logement','Electricité & Eau'),
('OUT','REDAL',           'Logement','Electricité & Eau'),
('OUT','AMENDIS',         'Logement','Electricité & Eau'),
('OUT','ONEE',            'Logement','Electricité & Eau'),
('OUT','ELECTRICITE',     'Logement','Electricité & Eau'),
('OUT','EAU',             'Logement','Electricité & Eau'),
('OUT','PLOMBIER',        'Logement','Entretien & Maison'),
('OUT','ELECTROMENAGER',  'Logement','Entretien & Maison'),
('OUT','IKEA',            'Logement','Entretien & Maison'),
('OUT','KITEA',           'Logement','Entretien & Maison'),
('OUT','SYNDIC',          'Logement','Charges & Taxes'),
('OUT','IMPOT',           'Logement','Charges & Taxes'),
('OUT','TAXE',            'Logement','Charges & Taxes'),
-- Vie Quotidienne (OUT)
('OUT','MARJANE',         'Vie Quotidienne','Courses maison'),
('OUT','CARREFOUR',       'Vie Quotidienne','Courses maison'),
('OUT','ACIMA',           'Vie Quotidienne','Courses maison'),
('OUT','ASWAK ASSALAM',   'Vie Quotidienne','Courses maison'),
('OUT','BIM',             'Vie Quotidienne','Courses maison'),
('OUT','LABEL VIE',       'Vie Quotidienne','Courses maison'),
('OUT','ATACADAO',        'Vie Quotidienne','Courses maison'),
('OUT','SUPERMARCHE',     'Vie Quotidienne','Courses maison'),
('OUT','COURSES',         'Vie Quotidienne','Courses maison'),
('OUT','EPICERIE',        'Vie Quotidienne','Courses maison'),
('OUT','HANOUT',          'Vie Quotidienne','Courses maison'),
('OUT','BOUCHERIE',       'Vie Quotidienne','Alimentation'),
('OUT','POULET',          'Vie Quotidienne','Alimentation'),
('OUT','VIANDE',          'Vie Quotidienne','Alimentation'),
('OUT','POISSON',         'Vie Quotidienne','Alimentation'),
('OUT','SOUK',            'Vie Quotidienne','Alimentation'),
('OUT','LEGUMES',         'Vie Quotidienne','Alimentation'),
('OUT','FRUITS',          'Vie Quotidienne','Alimentation'),
('OUT','PRIMEUR',         'Vie Quotidienne','Alimentation'),
('OUT','CAFE',            'Vie Quotidienne','Snacks & Boissons'),
('OUT','SNACK',           'Vie Quotidienne','Snacks & Boissons'),
('OUT','PATISSERIE',      'Vie Quotidienne','Snacks & Boissons'),
('OUT','BOULANGERIE',     'Vie Quotidienne','Snacks & Boissons'),
('OUT','STARBUCKS',       'Vie Quotidienne','Snacks & Boissons'),
('OUT','PAUL',            'Vie Quotidienne','Snacks & Boissons'),
('OUT','MCDONALD',        'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','MCDO',            'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','BURGER KING',     'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','KFC',             'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','PIZZA',           'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','TACOS',           'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','RESTAURANT',      'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','RESTO',           'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','LIVRAISON',       'Vie Quotidienne','Restaurant rapide & fast food'),
('OUT','GLOVO',           'Vie Quotidienne','Restaurant rapide & fast food'),
-- Transport (OUT)
('OUT','ESSENCE',         'Transport','Carburant'),
('OUT','GASOIL',          'Transport','Carburant'),
('OUT','STATION',         'Transport','Carburant'),
('OUT','AFRIQUIA',        'Transport','Carburant'),
('OUT','SHELL',           'Transport','Carburant'),
('OUT','TOTAL',           'Transport','Carburant'),
('OUT','CARBURANT',       'Transport','Carburant'),
('OUT','TRAMWAY',         'Transport','Taxi & Transports'),
('OUT','TRAM',            'Transport','Taxi & Transports'),
('OUT','ALSA',            'Transport','Taxi & Transports'),
('OUT','TAXI',            'Transport','Taxi & Transports'),
('OUT','UBER',            'Transport','Taxi & Transports'),
('OUT','INDRIVER',        'Transport','Taxi & Transports'),
('OUT','CAREEM',          'Transport','Taxi & Transports'),
('OUT','LAVAGE',          'Transport','Entretien & Réparation'),
('OUT','VIDANGE',         'Transport','Entretien & Réparation'),
('OUT','MECANICIEN',      'Transport','Entretien & Réparation'),
('OUT','GARAGE',          'Transport','Entretien & Réparation'),
('OUT','PNEU',            'Transport','Entretien & Réparation'),
('OUT','ASSURANCE AUTO',  'Transport','Assurance & Vignette'),
('OUT','VIGNETTE',        'Transport','Assurance & Vignette'),
('OUT','VISITE TECHNIQUE','Transport','Assurance & Vignette'),
('OUT','PARKING',         'Transport','Parking & Péage'),
('OUT','PEAGE',           'Transport','Parking & Péage'),
('OUT','AUTOROUTE',       'Transport','Parking & Péage'),
-- Loisirs (OUT)
('OUT','ZARA',            'Loisirs','Sorties & Culture'),
('OUT','H&M',             'Loisirs','Sorties & Culture'),
('OUT','DECATHLON',       'Loisirs','Sorties & Culture'),
('OUT','SHOPPING',        'Loisirs','Sorties & Culture'),
('OUT','VETEMENT',        'Loisirs','Sorties & Culture'),
('OUT','CHAUSSURE',       'Loisirs','Sorties & Culture'),
('OUT','CINEMA',          'Loisirs','Sorties & Culture'),
('OUT','MEGARAMA',        'Loisirs','Sorties & Culture'),
('OUT','IMAX',            'Loisirs','Sorties & Culture'),
('OUT','LIVRE',           'Loisirs','Sorties & Culture'),
('OUT','VOYAGE',          'Loisirs','Voyages & Weekend'),
('OUT','HOTEL',           'Loisirs','Voyages & Weekend'),
('OUT','RIAD',            'Loisirs','Voyages & Weekend'),
('OUT','AIRBNB',          'Loisirs','Voyages & Weekend'),
('OUT','RYANAIR',         'Loisirs','Voyages & Weekend'),
('OUT','ROYAL AIR MAROC', 'Loisirs','Voyages & Weekend'),
('OUT','ONCF',            'Loisirs','Voyages & Weekend'),
('OUT','TRAIN',           'Loisirs','Voyages & Weekend'),
('OUT','SPORT',           'Loisirs','Sport & Bien-être'),
('OUT','SALLE DE SPORT',  'Loisirs','Sport & Bien-être'),
('OUT','PISCINE',         'Loisirs','Sport & Bien-être'),
('OUT','FOOTBALL',        'Loisirs','Sport & Bien-être'),
('OUT','COIFFEUR',        'Loisirs','Sport & Bien-être'),
('OUT','BARBIER',         'Loisirs','Sport & Bien-être'),
('OUT','HAMMAM',          'Loisirs','Sport & Bien-être'),
('OUT','PARFUM',          'Loisirs','Sport & Bien-être'),
('OUT','COSMETIQUE',      'Loisirs','Sport & Bien-être'),
('OUT','CADEAU',          'Loisirs','Cadeaux & Dons'),
('OUT','ANNIVERSAIRE',    'Loisirs','Cadeaux & Dons'),
('OUT','MARIAGE',         'Loisirs','Cadeaux & Dons'),
-- Abonnements (OUT)
('OUT','MAROC TELECOM',   'Abonnements','Télécom & Internet'),
('OUT','INWI',            'Abonnements','Télécom & Internet'),
('OUT','ORANGE',          'Abonnements','Télécom & Internet'),
('OUT','INTERNET',        'Abonnements','Télécom & Internet'),
('OUT','WIFI',            'Abonnements','Télécom & Internet'),
('OUT','FORFAIT',         'Abonnements','Télécom & Internet'),
('OUT','RECHARGE',        'Abonnements','Télécom & Internet'),
('OUT','NETFLIX',         'Abonnements','Streaming & Apps'),
('OUT','SPOTIFY',         'Abonnements','Streaming & Apps'),
('OUT','YOUTUBE',         'Abonnements','Streaming & Apps'),
('OUT','DISNEY',          'Abonnements','Streaming & Apps'),
('OUT','APPLE MUSIC',     'Abonnements','Streaming & Apps'),
('OUT','CHATGPT',         'Abonnements','Streaming & Apps'),
('OUT','CLAUDE',          'Abonnements','Streaming & Apps'),
('OUT','GITHUB',          'Abonnements','Streaming & Apps'),
('OUT','ADOBE',           'Abonnements','Streaming & Apps'),
('OUT','MICROSOFT',       'Abonnements','Streaming & Apps'),
('OUT','GOOGLE ONE',      'Abonnements','Streaming & Apps'),
('OUT','ICLOUD',          'Abonnements','Streaming & Apps'),
('OUT','GYM',             'Abonnements','Club & Gym'),
('OUT','FITNESS',         'Abonnements','Club & Gym'),
('OUT','CLUB',            'Abonnements','Club & Gym'),
('OUT','BANQUE',          'Abonnements','Abonnements_autre'),
('OUT','ASSURANCE',       'Abonnements','Abonnements_autre'),
('OUT','CIH',             'Abonnements','Abonnements_autre'),
('OUT','BMCE',            'Abonnements','Abonnements_autre'),
('OUT','ATTIJARIWAFA',    'Abonnements','Abonnements_autre'),
('OUT','BANQUE POPULAIRE','Abonnements','Abonnements_autre'),
-- Santé (OUT)
('OUT','PHARMACIE',       'Santé','Pharmacie'),
('OUT','MEDICAMENT',      'Santé','Pharmacie'),
('OUT','PARAPHARMACIE',   'Santé','Pharmacie'),
('OUT','MEDECIN',         'Santé','Médecin & Examens'),
('OUT','DOCTEUR',         'Santé','Médecin & Examens'),
('OUT','DENTISTE',        'Santé','Médecin & Examens'),
('OUT','CLINIQUE',        'Santé','Médecin & Examens'),
('OUT','HOPITAL',         'Santé','Médecin & Examens'),
('OUT','ANALYSE',         'Santé','Médecin & Examens'),
('OUT','RADIO',           'Santé','Médecin & Examens'),
('OUT','SCANNER',         'Santé','Médecin & Examens'),
('OUT','LABO',            'Santé','Médecin & Examens'),
('OUT','LUNETTES',        'Santé','Optique'),
('OUT','OPTICIEN',        'Santé','Optique'),
('OUT','LENTILLES',       'Santé','Optique'),
-- Finances & Crédits (OUT)
('OUT','CREDIT',          'Finances & Crédits','Crédit & Remboursement'),
('OUT','ECHEANCE',        'Finances & Crédits','Crédit & Remboursement'),
('OUT','MENSUALITE',      'Finances & Crédits','Crédit & Remboursement'),
('OUT','DETTE',           'Finances & Crédits','Crédit & Remboursement'),
('OUT','EPARGNE',         'Finances & Crédits','Épargne & Investissement'),
('OUT','INVESTISSEMENT',  'Finances & Crédits','Épargne & Investissement'),
('OUT','FRAIS BANCAIRES', 'Finances & Crédits','Frais Bancaires'),
('OUT','COMMISSION',      'Finances & Crédits','Frais Bancaires'),
-- Divers (OUT)
('OUT','AMENDE',          'Divers','Amendes'),
('OUT','CONTRAVENTION',   'Divers','Amendes'),
('OUT','TIMBRE',          'Divers','Administratif'),
('OUT','NOTAIRE',         'Divers','Administratif'),
('OUT','DOSSIER',         'Divers','Administratif'),
('OUT','TELEPHONE',       'Divers','Objets du quotidien'),
('OUT','SAMSUNG',         'Divers','Objets du quotidien'),
('OUT','APPLE',           'Divers','Objets du quotidien'),
('OUT','IPHONE',          'Divers','Objets du quotidien')
ON CONFLICT ("Sens","Mot_Cle") DO NOTHING;
